FormProject/FormApp/urls.py
from django.urls import path #画面遷移を定義
from . import views


app_name = 'form_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('form_page/', views.form_page, name='form_page'),
    path('form_post/', views.form_post, name='form_post')
] # 遷移する画面を２つ定義

FormProject/FormProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('form_app/', include('FormApp.urls')),
]

FormProject/FormApp/models.py
from django.db import models

# Create your models here.
class Post(models. Model):
    name = models.CharField(max_length=50)
    title = models.CharField(max_length=255)
    memo = models.CharField(max_length=255)
    

FormProject/FormApp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from .models import Post

def check_name(value):
    if value == 'あああああ':
        raise ValidationError('その名前は登録できない')
class UserInfo(forms.Form):
    name = forms.CharField(label='名前', min_length=5, max_length=10, validators=[check_name])
    age = forms.IntegerField(label='年齢', validators=[MinValueValidator(20, message='20以上にしましょう')])
    mail = forms.EmailField(
        label='メールアドレス',
        widget=forms.TextInput(attrs={'class':'mail_class', 'placeholder': 'sample@mail.com'})
        )
    verify_mail = forms.EmailField(
        label='メールアドレス再入力',
        widget=forms.TextInput(attrs={'class':'mail_class', 'placeholder': 'sample@mail.com'})
        )
    is_married = forms.BooleanField(initial=True) # TrueかFalseを入れるFieldチェックボックス # initial→初期値を設定
    birthday = forms.DateField(initial='1990-01-01') # 日付を入れるField
    salary = forms.DecimalField() # 正確な数値を入れる
    job = forms.ChoiceField(choices=(
        (1, '正社員'),
        (2, '自営業'),
        (3, '学生'),
        (4, '無職')
    ), widget=forms.RadioSelect) # ラジオボタン # セレクトボックス4つの選択肢から1つ選ぶ
    hobbies = forms.MultipleChoiceField(choices=(
        (1, 'スポーツ'),
        (2, '読書'),
        (3, '映画鑑賞'),
        (4, 'その他')
    ), widget=forms.CheckboxSelectMultiple) # チェックボックス
    homepage = forms.URLField(required=False) # このFieldに何も入れなくてもエラーが出ない
    memo = forms.CharField(widget=forms.Textarea) # テキストに複数行入力できる

    def __init__(self, *args, **kwargs):
        super(UserInfo, self).__init__(*args, **kwargs)
        self.fields['job'].widget.attrs['id'] = 'id_job'
        self.fields['hobbies'].widget.attrs['class'] = 'hobbies_class'

    def clean_homepage(self):
        homepage = self.cleaned_data['homepage']
        if not homepage.startswith('https'):
            raise forms.ValidationError('ホームページのURLはhttpsのみ')


    def clean(self):
        cleaned_data = super().clean()
        mail = cleaned_data['mail']
        verify_mail = cleaned_data['verify_mail']
        if mail != verify_mail:
            raise forms.ValidationError('メールアドレスが一致しません')


class BaseForm(forms.ModelForm):
    def save(self, *args, **kwargs):
        print(f'Form: {self.__class__.__name__}実行')
        return super(BaseForm, self).save(*args, **kwargs)


class PostModelForm(forms.ModelForm):
    name = forms.CharField(label='名前')
    title = forms.CharField(label='タイトル')
    memo = forms.CharField(
        label='メモ', widget=forms.Textarea(attrs={'rows': 30, 'cols': 20})
    )    # テキストエリア　改行もできるように
    class Meta:
        model = Post
        fields = '__all__' # 画面上にどのfieldを表示するのか（全field）
        # fields = ['name', 'title']
        # exclude = ['title']

    def save(self, *args, **kwargs):
        obj = super(PostModelForm, self).save(commit=False, *args, **kwargs)
        obj.name = obj.name.upper()
        print(type(obj))
        print('save実行')
        obj.save()
        return obj
    
    def clean_name(self):
        name = self.cleaned_data.get('name')
        if name == 'ああああ':
            raise ValidationError('名前が登録できません')
        return name

FormProject/FormApp/views.py
from django.shortcuts import render
from . import forms
# Create your views here.

def index(request):
    return render(request, 'formapp/index.html')

def form_page(request):
    form = forms.UserInfo()
    if request.method == 'POST':
        # Formで送られたデータを取り出す
        form = forms.UserInfo(request.POST)
        if form.is_valid():# バリデーション（フィールドが正しいかチェック）
            print('バリデーション成功')
            print(
                f"name: {form.cleaned_data['name']}, mail: {form.cleaned_data['mail']}, age: {form.cleaned_data['age']}"
            ) # formからname,mail,ageを取り出す
            print(form.cleaned_data)
    return render(
        request, 'formapp/form_page.html',context={
            'form': form
        } # formをcontextとして値を渡す
    )


def form_post(request):
    form = forms.PostModelForm()
    if request.method == 'POST':
        form = forms.PostModelForm(request.POST)
        if form.is_valid():
            form.save()
    return render(
        request, 'formapp/form_post.html', context={'form': form}
    ) # formappのform_post.htmlから画面表示

FormProject/templates/formapp/form_page.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <title>Form</title>
    {% load static %} {#静的ファイルを読み込む#}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
  print("form: ", form)
  print("dir(form): ", dir(form))
  </head>
  <body>
  <form method="POST"> {#送信ボタンの追加(CSRFトークンの設定がないと送信できない)#}
   {% csrf_token %}
  print("form: ", form)
  print("dir(form): ", dir(form))
  <table>
       {{form.as_table}} {#縦に表示#}
  </table>
    <input type="submit" value="送信">
  </form>
  </body>
</html>

FormProject/templates/formapp/form_post.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <title>Form</title>
    {% load static %} {#静的ファイルを読み込む#}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </html>
  <body>
  <form method="POST"> {#送信ボタンの追加(CSRFトークンの設定がないと送信できない)#}
   {% csrf_token %}
   {{ form.name.label}} : {{ form.name }}
   {% if form.name.errors %}
       <div style="color:red;">{{ form.name.errors.as_text }}</div>
   {% endif %}
   {{ form.title.label}} : {{ form.title }}
   {% if form.title.errors %}
       <div style="color:red;">{{ form.name.errors.as_text }}</div>
   {% endif %}
   {{ form.memo.label}} : {{ form.memo }}
   {% if form.memo.errors %}
       <div style="color:red;">{{ form.name.errors.as_text }}</div>
   {% endif %}
    <input type="submit" value="送信">
  </form>
  </body>
</html>

FormProject/templates/formapp/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <title>HOME</title>
  </head>
  <body>
    <h1>ホームページ</h1>
    <a href="{% url 'form_app:form_page' %}">フォーム画面へ</a>
  </body>
</html>